name: E2E tests

on:
  workflow_dispatch:

jobs:
  tests: 
    runs-on: ubuntu-latest

    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Instalando as dependências
        run: npm install

      - name: Iniciando servidor de mocks
        run: npm run mock-server &

      - name: Iniciando servidor aplicação web
        run: npm run server &

      - name: Executar os testes
        run: npx cypress run
